### ISSUE TITLE
The TrySetMember method is not working; it doesn't execute.

### ISSUE THREAD

**Issue by JAHC-DeV** [Marusyk/Simple.HttpPatch#13]
- The TrySetMember method never executes; therefore, _changedProperties remains empty, and as a result, it doesn't work.
- I tried with the example from the repository, and I get the same results; it doesn't work.
- Thank for your time :).

**Comment by Marusyk** [comment]
Hi @JAHC-DeV, thanks for your feedback.
Unfortunately, I don't have time for this project right now, but if you're interested, you can prepare a PR with these fixes

**Comment by ayrloong** [comment]
You can solve this problem using Microsoft.AspNetCore.Mvc.NewtonsoftJson  

services.AddControllers()
        .AddNewtonsoftJson();

**Comment by ayrloong** [comment]
I'll submit a PR to fix this issue. https://github.com/Marusyk/Simple.HttpPatch/pull/14
